repos:
-   repo: local
    hooks:
    -   id: nix fmt
        name: Nix fmt
        entry: nix fmt
        files: \.nix$
        language: system
    # -   id: nix lint
    #     name: Nix lint
    #     entry: nix run 'nixpkgs#nix-linter'
    #     files: \.nix$
    #     language: system
