repos:
  - repo: local
    hooks:
      - id: treefmt
        name: treefmt
        entry: nix fmt
        language: system
        pass_filenames: false
    # -   id: nix lint
    #     name: Nix lint
    #     entry: nix run 'nixpkgs#nix-linter'
    #     files: \.nix$
    #     language: system
