[colors]
background       = '#e8f0ff'
black            = '#e8f0ff'
blue             = '#1e66f5'
cursor           = '#24273a'
cyan             = '#179299'
foreground       = '#24273a'
green            = '#40a02b'
magenta          = '#8839ef'
red              = '#d20f39'
tabs             = '#e1e4e8'
tabs-active      = '#ccd0da'
white            = '#24273a'
yellow           = '#df8e1d'
dim-black        = '#dce0e8'
dim-blue         = '#1752c9'
dim-cyan         = '#127680'
dim-foreground   = '#1c1f2e'
dim-green        = '#357f23'
dim-magenta      = '#722fc3'
dim-red          = '#a90c2e'
dim-white        = '#1c1f2e'
dim-yellow       = '#b57418'
light-black      = '#5b6078'
light-blue       = '#267ff5'
light-cyan       = '#1da6ad'
light-foreground = '#2c2f3d'
light-green      = '#4db332'
light-magenta    = '#9c46f5'
light-red        = '#e42144'
light-white      = '#363a4f'
light-yellow     = '#f29d23'
