[colors]
background       = '#24273a'
black            = '#24273a'
blue             = '#8aadf4'
cursor           = '#e8f0ff'
cyan             = '#8bd5ca'
foreground       = '#e8f0ff'
green            = '#a6da95'
magenta          = '#cba6f7'
red              = '#ed8796'
tabs             = '#363a4f'
tabs-active      = '#494d64'
white            = '#e8f0ff'
yellow           = '#eed49f'
dim-black        = '#1e2030'
dim-blue         = '#7891d0'
dim-cyan         = '#73b9a8'
dim-foreground   = '#b0b7d0'
dim-green        = '#8cb77d'
dim-magenta      = '#ad92d5'
dim-red          = '#c9707d'
dim-white        = '#b0b7d0'
dim-yellow       = '#d1bc87'
light-black      = '#5b6078'
light-blue       = '#74c7ec'
light-cyan       = '#aee2da'
light-foreground = '#747c9e'
light-green      = '#68f288'
light-magenta    = '#f5bde6'
light-red        = '#ff5370'
light-white      = '#747c9e'
light-yellow     = '#fab387'
