[colors]
background       = '#000000'
black            = '#000000'
blue             = '#0087d7'
cursor           = '#ffffff'
cyan             = '#00afaf'
foreground       = '#d0d0d0'
green            = '#00af5f'
magenta          = '#d787d7'
red              = '#d7005f'
tabs             = '#1c1c1c'
tabs-active      = '#303030'
white            = '#d0d0d0'
yellow           = '#d78700'
dim-black        = '#262626'
dim-blue         = '#005faf'
dim-cyan         = '#008787'
dim-foreground   = '#8a8a8a'
dim-green        = '#008700'
dim-magenta      = '#875f87'
dim-red          = '#af005f'
dim-white        = '#8a8a8a'
dim-yellow       = '#af8700'
light-black      = '#767676'
light-blue       = '#00afff'
light-cyan       = '#00d7d7'
light-foreground = '#ffffff'
light-green      = '#00d75f'
light-magenta    = '#ff87ff'
light-red        = '#ff5f87'
light-white      = '#ffffff'
light-yellow     = '#ffaf00'
