[colors]
background       = '#ffffff'
black            = '#000000'
blue             = '#005faf'
cursor           = '#000000'
cyan             = '#008787'
foreground       = '#000000'
green            = '#008700'
magenta          = '#870087'
red              = '#af0000'
tabs             = '#e4e4e4'
tabs-active      = '#d0d0d0'
white            = '#ffffff'
yellow           = '#af5f00'
dim-black        = '#262626'
dim-blue         = '#00305f'
dim-cyan         = '#005f5f'
dim-foreground   = '#585858'
dim-green        = '#005f00'
dim-magenta      = '#5f005f'
dim-red          = '#870000'
dim-white        = '#d0d0d0'
dim-yellow       = '#875f00'
light-black      = '#585858'
light-blue       = '#0087d7'
light-cyan       = '#00afaf'
light-foreground = '#262626'
light-green      = '#00af5f'
light-magenta    = '#af00af'
light-red        = '#d70000'
light-white      = '#ffffff'
light-yellow     = '#d78700'
